language: go

go:
  - "1.13"

env:
  - GO111MODULE=on

install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
  - docker pull postgres:11-alpine
  - docker pull mysql:5.7

script:
  - ./build+test.sh
