language: go

go:
  - "1.13"

env:
  - GO111MODULE=on

services:
  - mysql
  - postgresql

install:
  - go get -t -v ./...
  - go install github.com/mattn/goveralls

script:
  - ./build+test.sh
  - ./test.sh all
