language: go

go:
  - "1.15"

env:
  global:
    - GO111MODULE=on
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=
    - PGDATABASE=test

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - psql -c 'CREATE DATABASE test;' -U postgres

install:
  - go install github.com/mattn/goveralls

script:
  - ./build+test.sh
  - ./test.sh all
  - ./pgxapi/pgtest.sh travis

