language: go

go:
  - "1.15"

env:
  global:
    - GO111MODULE=on
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=
    - PGDATABASE=test
    - MYUSER=travis
    - MYPASSWORD=

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - go install github.com/mattn/goveralls

script:
  - ./build+test.sh travis

